Update adl to 0.13.2, and use released platform binaries instead of the helix docker container.

diff --git a/scripts/adlc b/scripts/adlc
--- a/scripts/adlc
+++ b/scripts/adlc
@@ -1,5 +1,33 @@
 #!/bin/bash
-# Run the adl compiler using the published docker container
+# 
+# script that downloads and caches the adl compiler if necessary, and then
+# runs it.
 
-ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null && pwd )"
-exec $ROOT/scripts/adlenv adlc "$@"
+set -e
+
+adlversion=0.13.2
+
+if [ "$(uname)" == "Darwin" ]; then
+  platform=osx
+  cachedir=$HOME/Library/Caches/adl
+elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+  platform=linux
+  cachedir=$HOME/.cache/adl 
+else
+  echo "Unable to download ADL for platform"
+  exit 1
+fi
+
+downloads=$cachedir/downloads
+release=https://github.com/timbod7/adl/releases/download/v$adlversion/adl-bindist-$adlversion-$platform.zip
+
+if [ ! -d "$cachedir/$adlversion" ]; then
+  echo "fetching $release ..."
+  mkdir -p $downloads
+  (cd $downloads; wget -q $release || (echo "download failed"; exit 1))
+  mkdir -p $cachedir/$adlversion
+  (cd $cachedir/$adlversion; unzip -q $downloads/$(basename $release))
+fi
+
+exec $cachedir/$adlversion/bin/adlc "$@"
+
